name: Latch Pod Checker

on:
  schedule:
    - cron: "50 01 * * *"  
  workflow_dispatch:  

jobs:
  check-pod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Configure SSH and run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host latch-pod\n  HostName 172.20.203.63\n  User root\n  ProxyJump root@a1fd7b5d7b5824b46b8671207e1124b6-610912349.us-west-2.elb.amazonaws.com" >> ~/.ssh/config
          ssh-keyscan -H 172.20.203.63 >> ~/.ssh/known_hosts
          ssh-keyscan -H a1fd7b5d7b5824b46b8671207e1124b6-610912349.us-west-2.elb.amazonaws.com >> ~/.ssh/known_hosts
          python check_latch_pod.py
